language: python
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
install:
- pip install .[test]
script:
- python setup.py check -rms
- flake8
# - travis_wait pytest -s -v tests/
deploy:
  skip_cleanup: true
  distributions: sdist bdist_wheel
  provider: pypi
  on:
    tags: true
    branch: master
    python: '3.7'