language: python
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
install:
- pip install .[test]
script:
- python setup.py check -rms
- flake8
deploy:
  skip_cleanup: true
  distributions: sdist bdist_wheel
  provider: pypi
  on:
    tags: true
    branch: master
    python: '3.7'
  password:
    secure: TBok/QLxoUh0lf651OUi6gh+kNc3taoaarygnjTnhEPot91rzMorPTlShWvoIGjH+FkanTEijqjNVcRFDAx0vJLzdTIPWBmHnLq2tE2+8kM7tYDam5hMVd1cr/BHRPN/mx8Jk0wZGD7TDjSFW0zvBI0SdYCY6xEc7ldsGl+KyzTPw9Ub3MhIqTSK8x5EZXCm4KWt+C41RGCfX85yLgAIeJ8VDVLZy0InNQh79/zWRmhdfqse5ojjjLJ0rOwlSfdAXhFUYdONQ7IgRX/iiZufpyHfuJ1fElyBBUGG2eX4hmvsvTg8w4HRBZ/sNDX4+7EH4cjDyS5sRkQQ8HHdvXKArAR658QVJCDuvQxk9BWzp/mb9euJ/3a9iykNxW3xuJym1RykfZVhFk9Q3mAPkEHBMrblPI6gdL8RfBp3G2AIDOXUhyDPrY4yXh3mpO0Ck320YvHzCP9JrZ2B8Pz+D6y6zUz1P/qQf2MXhvNBtv9/U0BrZtfGFqYzmQQ0ZM2L6mMp0u+Xu81qj/VQhPOBFlNJVNIA+xiCujA/lp6GHblMV09ztTXVujZFYd6N0qLw36SPJQu4G7tq0ofwWeWJLqon9j8WAk8jFwUpKhZyxU3cxQ8UbXYarj20DuVx8RQN78sA0V+0cDqXB7WLzDLsp5f/gOdcDMQyYoaN3Kqm1BhKJ88=
